// List of countries with time zones (195 sovereign states)
export const COUNTRIES = [
  { name: "Poland", timezone: "Europe/Warsaw", locale: "pl-PL" },
  { name: "Afghanistan", timezone: "Asia/Kabul", locale: "fa-AF" },
  { name: "Albania", timezone: "Europe/Tirane", locale: "sq-AL" },
  { name: "Algeria", timezone: "Africa/Algiers", locale: "ar-DZ" },
  { name: "Andorra", timezone: "Europe/Andorra", locale: "ca-AD" },
  { name: "Angola", timezone: "Africa/Luanda", locale: "pt-AO" },
  { name: "Antigua and Barbuda", timezone: "America/Antigua", locale: "en-AG" },
  {
    name: "Argentina",
    timezone: "America/Argentina/Buenos_Aires",
    locale: "es-AR",
  },
  { name: "Armenia", timezone: "Asia/Yerevan", locale: "hy-AM" },
  { name: "Australia", timezone: "Australia/Sydney", locale: "en-AU" },
  { name: "Austria", timezone: "Europe/Vienna", locale: "de-AT" },
  { name: "Azerbaijan", timezone: "Asia/Baku", locale: "az-AZ" },
  { name: "Bahamas", timezone: "America/Nassau", locale: "en-BS" },
  { name: "Bahrain", timezone: "Asia/Bahrain", locale: "ar-BH" },
  { name: "Bangladesh", timezone: "Asia/Dhaka", locale: "bn-BD" },
  { name: "Barbados", timezone: "America/Barbados", locale: "en-BB" },
  { name: "Belarus", timezone: "Europe/Minsk", locale: "be-BY" },
  { name: "Belgium", timezone: "Europe/Brussels", locale: "nl-BE" },
  { name: "Belize", timezone: "America/Belize", locale: "en-BZ" },
  { name: "Benin", timezone: "Africa/Porto-Novo", locale: "fr-BJ" },
  { name: "Bhutan", timezone: "Asia/Thimphu", locale: "dz-BT" },
  { name: "Bolivia", timezone: "America/La_Paz", locale: "es-BO" },
  {
    name: "Bosnia and Herzegovina",
    timezone: "Europe/Sarajevo",
    locale: "bs-BA",
  },
  { name: "Botswana", timezone: "Africa/Gaborone", locale: "en-BW" },
  { name: "Brazil", timezone: "America/Sao_Paulo", locale: "pt-BR" },
  { name: "Brunei", timezone: "Asia/Brunei", locale: "ms-BN" },
  { name: "Bulgaria", timezone: "Europe/Sofia", locale: "bg-BG" },
  { name: "Burkina Faso", timezone: "Africa/Ouagadougou", locale: "fr-BF" },
  { name: "Burundi", timezone: "Africa/Bujumbura", locale: "rn-BI" },
  { name: "Cabo Verde", timezone: "Atlantic/Cape_Verde", locale: "pt-CV" },
  { name: "Cambodia", timezone: "Asia/Phnom_Penh", locale: "km-KH" },
  { name: "Cameroon", timezone: "Africa/Douala", locale: "fr-CM" },
  { name: "Canada", timezone: "America/Toronto", locale: "en-CA" },
  {
    name: "Central African Republic",
    timezone: "Africa/Bangui",
    locale: "fr-CF",
  },
  { name: "Chad", timezone: "Africa/Ndjamena", locale: "fr-TD" },
  { name: "Chile", timezone: "America/Santiago", locale: "es-CL" },
  { name: "China", timezone: "Asia/Shanghai", locale: "zh-CN" },
  { name: "Colombia", timezone: "America/Bogota", locale: "es-CO" },
  { name: "Comoros", timezone: "Indian/Comoro", locale: "ar-KM" },
  {
    name: "Congo (Republic of the)",
    timezone: "Africa/Brazzaville",
    locale: "fr-CG",
  },
  { name: "Costa Rica", timezone: "America/Costa_Rica", locale: "es-CR" },
  { name: "Côte d'Ivoire", timezone: "Africa/Abidjan", locale: "fr-CI" },
  { name: "Croatia", timezone: "Europe/Zagreb", locale: "hr-HR" },
  { name: "Cuba", timezone: "America/Havana", locale: "es-CU" },
  { name: "Cyprus", timezone: "Asia/Nicosia", locale: "el-CY" },
  { name: "Czechia", timezone: "Europe/Prague", locale: "cs-CZ" },
  {
    name: "Democratic Republic of the Congo",
    timezone: "Africa/Kinshasa",
    locale: "fr-CD",
  },
  { name: "Denmark", timezone: "Europe/Copenhagen", locale: "da-DK" },
  { name: "Djibouti", timezone: "Africa/Djibouti", locale: "fr-DJ" },
  { name: "Dominica", timezone: "America/Dominica", locale: "en-DM" },
  {
    name: "Dominican Republic",
    timezone: "America/Santo_Domingo",
    locale: "es-DO",
  },
  { name: "Ecuador", timezone: "America/Guayaquil", locale: "es-EC" },
  { name: "Egypt", timezone: "Africa/Cairo", locale: "ar-EG" },
  { name: "El Salvador", timezone: "America/El_Salvador", locale: "es-SV" },
  { name: "Equatorial Guinea", timezone: "Africa/Malabo", locale: "es-GQ" },
  { name: "Eritrea", timezone: "Africa/Asmara", locale: "ti-ER" },
  { name: "Estonia", timezone: "Europe/Tallinn", locale: "et-EE" },
  { name: "Eswatini", timezone: "Africa/Mbabane", locale: "en-SZ" },
  { name: "Ethiopia", timezone: "Africa/Addis_Ababa", locale: "am-ET" },
  { name: "Fiji", timezone: "Pacific/Fiji", locale: "en-FJ" },
  { name: "Finland", timezone: "Europe/Helsinki", locale: "fi-FI" },
  { name: "France", timezone: "Europe/Paris", locale: "fr-FR" },
  { name: "Gabon", timezone: "Africa/Libreville", locale: "fr-GA" },
  { name: "Gambia", timezone: "Africa/Banjul", locale: "en-GM" },
  { name: "Georgia", timezone: "Asia/Tbilisi", locale: "ka-GE" },
  { name: "Germany", timezone: "Europe/Berlin", locale: "de-DE" },
  { name: "Ghana", timezone: "Africa/Accra", locale: "en-GH" },
  { name: "Greece", timezone: "Europe/Athens", locale: "el-GR" },
  { name: "Grenada", timezone: "America/Grenada", locale: "en-GD" },
  { name: "Guatemala", timezone: "America/Guatemala", locale: "es-GT" },
  { name: "Guinea", timezone: "Africa/Conakry", locale: "fr-GN" },
  { name: "Guinea-Bissau", timezone: "Africa/Bissau", locale: "pt-GW" },
  { name: "Guyana", timezone: "America/Guyana", locale: "en-GY" },
  { name: "Haiti", timezone: "America/Port-au-Prince", locale: "fr-HT" },
  { name: "Honduras", timezone: "America/Tegucigalpa", locale: "es-HN" },
  { name: "Hungary", timezone: "Europe/Budapest", locale: "hu-HU" },
  { name: "Iceland", timezone: "Atlantic/Reykjavik", locale: "is-IS" },
  { name: "India", timezone: "Asia/Kolkata", locale: "hi-IN" },
  { name: "Indonesia", timezone: "Asia/Jakarta", locale: "id-ID" },
  { name: "Iran", timezone: "Asia/Tehran", locale: "fa-IR" },
  { name: "Iraq", timezone: "Asia/Baghdad", locale: "ar-IQ" },
  { name: "Ireland", timezone: "Europe/Dublin", locale: "en-IE" },
  { name: "Israel", timezone: "Asia/Jerusalem", locale: "he-IL" },
  { name: "Italy", timezone: "Europe/Rome", locale: "it-IT" },
  { name: "Jamaica", timezone: "America/Jamaica", locale: "en-JM" },
  { name: "Japan", timezone: "Asia/Tokyo", locale: "ja-JP" },
  { name: "Jordan", timezone: "Asia/Amman", locale: "ar-JO" },
  { name: "Kazakhstan", timezone: "Asia/Almaty", locale: "kk-KZ" },
  { name: "Kenya", timezone: "Africa/Nairobi", locale: "sw-KE" },
  { name: "Kiribati", timezone: "Pacific/Tarawa", locale: "en-KI" },
  { name: "Kuwait", timezone: "Asia/Kuwait", locale: "ar-KW" },
  { name: "Kyrgyzstan", timezone: "Asia/Bishkek", locale: "ky-KG" },
  { name: "Laos", timezone: "Asia/Vientiane", locale: "lo-LA" },
  { name: "Latvia", timezone: "Europe/Riga", locale: "lv-LV" },
  { name: "Lebanon", timezone: "Asia/Beirut", locale: "ar-LB" },
  { name: "Lesotho", timezone: "Africa/Maseru", locale: "en-LS" },
  { name: "Liberia", timezone: "Africa/Monrovia", locale: "en-LR" },
  { name: "Libya", timezone: "Africa/Tripoli", locale: "ar-LY" },
  { name: "Liechtenstein", timezone: "Europe/Zurich", locale: "de-LI" },
  { name: "Lithuania", timezone: "Europe/Vilnius", locale: "lt-LT" },
  { name: "Luxembourg", timezone: "Europe/Luxembourg", locale: "fr-LU" },
  { name: "Madagascar", timezone: "Indian/Antananarivo", locale: "fr-MG" },
  { name: "Malawi", timezone: "Africa/Blantyre", locale: "en-MW" },
  { name: "Malaysia", timezone: "Asia/Kuala_Lumpur", locale: "ms-MY" },
  { name: "Maldives", timezone: "Indian/Maldives", locale: "dv-MV" },
  { name: "Mali", timezone: "Africa/Bamako", locale: "fr-ML" },
  { name: "Malta", timezone: "Europe/Malta", locale: "mt-MT" },
  { name: "Marshall Islands", timezone: "Pacific/Majuro", locale: "en-MH" },
  { name: "Mauritania", timezone: "Africa/Nouakchott", locale: "ar-MR" },
  { name: "Mauritius", timezone: "Indian/Mauritius", locale: "en-MU" },
  { name: "Mexico", timezone: "America/Mexico_City", locale: "es-MX" },
  { name: "Micronesia", timezone: "Pacific/Pohnpei", locale: "en-FM" },
  { name: "Moldova", timezone: "Europe/Chisinau", locale: "ro-MD" },
  { name: "Monaco", timezone: "Europe/Monaco", locale: "fr-MC" },
  { name: "Mongolia", timezone: "Asia/Ulaanbaatar", locale: "mn-MN" },
  { name: "Montenegro", timezone: "Europe/Belgrade", locale: "sr-ME" },
  { name: "Morocco", timezone: "Africa/Casablanca", locale: "ar-MA" },
  { name: "Mozambique", timezone: "Africa/Maputo", locale: "pt-MZ" },
  { name: "Myanmar", timezone: "Asia/Yangon", locale: "my-MM" },
  { name: "Namibia", timezone: "Africa/Windhoek", locale: "en-NA" },
  { name: "Nauru", timezone: "Pacific/Nauru", locale: "en-NR" },
  { name: "Nepal", timezone: "Asia/Kathmandu", locale: "ne-NP" },
  { name: "Netherlands", timezone: "Europe/Amsterdam", locale: "nl-NL" },
  { name: "New Zealand", timezone: "Pacific/Auckland", locale: "en-NZ" },
  { name: "Nicaragua", timezone: "America/Managua", locale: "es-NI" },
  { name: "Niger", timezone: "Africa/Niamey", locale: "fr-NE" },
  { name: "Nigeria", timezone: "Africa/Lagos", locale: "en-NG" },
  { name: "North Korea", timezone: "Asia/Pyongyang", locale: "ko-KP" },
  { name: "North Macedonia", timezone: "Europe/Skopje", locale: "mk-MK" },
  { name: "Norway", timezone: "Europe/Oslo", locale: "nb-NO" },
  { name: "Oman", timezone: "Asia/Muscat", locale: "ar-OM" },
  { name: "Pakistan", timezone: "Asia/Karachi", locale: "ur-PK" },
  { name: "Palau", timezone: "Pacific/Palau", locale: "en-PW" },
  { name: "Palestine", timezone: "Asia/Hebron", locale: "ar-PS" },
  { name: "Panama", timezone: "America/Panama", locale: "es-PA" },
  {
    name: "Papua New Guinea",
    timezone: "Pacific/Port_Moresby",
    locale: "en-PG",
  },
  { name: "Paraguay", timezone: "America/Asuncion", locale: "es-PY" },
  { name: "Peru", timezone: "America/Lima", locale: "es-PE" },
  { name: "Philippines", timezone: "Asia/Manila", locale: "fil-PH" },
  { name: "Portugal", timezone: "Europe/Lisbon", locale: "pt-PT" },
  { name: "Qatar", timezone: "Asia/Qatar", locale: "ar-QA" },
  { name: "Romania", timezone: "Europe/Bucharest", locale: "ro-RO" },
  { name: "Russia", timezone: "Europe/Moscow", locale: "ru-RU" },
  { name: "Rwanda", timezone: "Africa/Kigali", locale: "rw-RW" },
  {
    name: "Saint Kitts and Nevis",
    timezone: "America/St_Kitts",
    locale: "en-KN",
  },
  { name: "Saint Lucia", timezone: "America/St_Lucia", locale: "en-LC" },
  {
    name: "Saint Vincent and the Grenadines",
    timezone: "America/St_Vincent",
    locale: "en-VC",
  },
  { name: "Samoa", timezone: "Pacific/Apia", locale: "sm-WS" },
  { name: "San Marino", timezone: "Europe/San_Marino", locale: "it-SM" },
  {
    name: "Sao Tome and Principe",
    timezone: "Africa/Sao_Tome",
    locale: "pt-ST",
  },
  { name: "Saudi Arabia", timezone: "Asia/Riyadh", locale: "ar-SA" },
  { name: "Senegal", timezone: "Africa/Dakar", locale: "fr-SN" },
  { name: "Serbia", timezone: "Europe/Belgrade", locale: "sr-RS" },
  { name: "Seychelles", timezone: "Indian/Mahe", locale: "fr-SC" },
  { name: "Sierra Leone", timezone: "Africa/Freetown", locale: "en-SL" },
  { name: "Singapore", timezone: "Asia/Singapore", locale: "en-SG" },
  { name: "Slovakia", timezone: "Europe/Bratislava", locale: "sk-SK" },
  { name: "Slovenia", timezone: "Europe/Ljubljana", locale: "sl-SI" },
  { name: "Solomon Islands", timezone: "Pacific/Guadalcanal", locale: "en-SB" },
  { name: "Somalia", timezone: "Africa/Mogadishu", locale: "so-SO" },
  { name: "South Africa", timezone: "Africa/Johannesburg", locale: "en-ZA" },
  { name: "South Korea", timezone: "Asia/Seoul", locale: "ko-KR" },
  { name: "South Sudan", timezone: "Africa/Juba", locale: "en-SS" },
  { name: "Spain", timezone: "Europe/Madrid", locale: "es-ES" },
  { name: "Sri Lanka", timezone: "Asia/Colombo", locale: "si-LK" },
  { name: "Sudan", timezone: "Africa/Khartoum", locale: "ar-SD" },
  { name: "Suriname", timezone: "America/Paramaribo", locale: "nl-SR" },
  { name: "Sweden", timezone: "Europe/Stockholm", locale: "sv-SE" },
  { name: "Switzerland", timezone: "Europe/Zurich", locale: "de-CH" },
  { name: "Syria", timezone: "Asia/Damascus", locale: "ar-SY" },
  { name: "Tajikistan", timezone: "Asia/Dushanbe", locale: "tg-TJ" },
  { name: "Tanzania", timezone: "Africa/Dar_es_Salaam", locale: "sw-TZ" },
  { name: "Thailand", timezone: "Asia/Bangkok", locale: "th-TH" },
  { name: "Timor-Leste", timezone: "Asia/Dili", locale: "pt-TL" },
  { name: "Togo", timezone: "Africa/Lome", locale: "fr-TG" },
  { name: "Tonga", timezone: "Pacific/Tongatapu", locale: "to-TO" },
  {
    name: "Trinidad and Tobago",
    timezone: "America/Port_of_Spain",
    locale: "en-TT",
  },
  { name: "Tunisia", timezone: "Africa/Tunis", locale: "ar-TN" },
  { name: "Turkey", timezone: "Europe/Istanbul", locale: "tr-TR" },
  { name: "Turkmenistan", timezone: "Asia/Ashgabat", locale: "tk-TM" },
  { name: "Tuvalu", timezone: "Pacific/Funafuti", locale: "en-TV" },
  { name: "Uganda", timezone: "Africa/Kampala", locale: "en-UG" },
  { name: "Ukraine", timezone: "Europe/Kyiv", locale: "uk-UA" },
  { name: "United Arab Emirates", timezone: "Asia/Dubai", locale: "ar-AE" },
  { name: "United Kingdom", timezone: "Europe/London", locale: "en-GB" },
  { name: "United States", timezone: "America/New_York", locale: "en-US" },
  { name: "Uruguay", timezone: "America/Montevideo", locale: "es-UY" },
  { name: "Uzbekistan", timezone: "Asia/Tashkent", locale: "uz-UZ" },
  { name: "Vanuatu", timezone: "Pacific/Efate", locale: "bi-VU" },
  { name: "Vatican City", timezone: "Europe/Rome", locale: "it-VA" },
  { name: "Venezuela", timezone: "America/Caracas", locale: "es-VE" },
  { name: "Vietnam", timezone: "Asia/Ho_Chi_Minh", locale: "vi-VN" },
  { name: "Yemen", timezone: "Asia/Aden", locale: "ar-YE" },
  { name: "Zambia", timezone: "Africa/Lusaka", locale: "en-ZM" },
  { name: "Zimbabwe", timezone: "Africa/Harare", locale: "en-ZW" },
];
