// List of countries with time zones
export const COUNTRIES = [
  { name: "Poland", timezone: "Europe/Warsaw", locale: "pl-PL", fixed: true },
  { name: "Australia (Sydney)", timezone: "Australia/Sydney", locale: "en-AU" },
  {
    name: "Brazil (São Paulo)",
    timezone: "America/Sao_Paulo",
    locale: "pt-BR",
  },
  { name: "Bulgaria", timezone: "Europe/Sofia", locale: "bg-BG" },
  { name: "China (Beijing)", timezone: "Asia/Shanghai", locale: "zh-CN" },
  { name: "Dubai (UAE)", timezone: "Asia/Dubai", locale: "ar-AE" },
  { name: "Egypt", timezone: "Africa/Cairo", locale: "ar-EG" },
  { name: "Estonia", timezone: "Europe/Tallinn", locale: "et-EE" },
  { name: "Finland", timezone: "Europe/Helsinki", locale: "fi-FI" },
  { name: "Greece", timezone: "Europe/Athens", locale: "el-GR" },
  { name: "Spain", timezone: "Europe/Madrid", locale: "es-ES" },
  { name: "Netherlands", timezone: "Europe/Amsterdam", locale: "nl-NL" },
  { name: "India (Delhi)", timezone: "Asia/Kolkata", locale: "hi-IN" },
  { name: "Indonesia (Jakarta)", timezone: "Asia/Jakarta", locale: "id-ID" },
  { name: "Iraq (Baghdad)", timezone: "Asia/Baghdad", locale: "ar-IQ" },
  { name: "Iran (Tehran)", timezone: "Asia/Tehran", locale: "fa-IR" },
  { name: "Ireland", timezone: "Europe/Dublin", locale: "en-IE" },
  { name: "Iceland", timezone: "Atlantic/Reykjavik", locale: "is-IS" },
  { name: "Israel", timezone: "Asia/Jerusalem", locale: "he-IL" },
  { name: "Japan (Tokyo)", timezone: "Asia/Tokyo", locale: "ja-JP" },
  { name: "Canada (Toronto)", timezone: "America/Toronto", locale: "en-CA" },
  {
    name: "Canada (Vancouver)",
    timezone: "America/Vancouver",
    locale: "en-CA",
  },
  { name: "South Korea (Seoul)", timezone: "Asia/Seoul", locale: "ko-KR" },
  { name: "Lithuania", timezone: "Europe/Vilnius", locale: "lt-LT" },
  { name: "Latvia", timezone: "Europe/Riga", locale: "lv-LV" },
  { name: "Mexico", timezone: "America/Mexico_City", locale: "es-MX" },
  { name: "New Zealand", timezone: "Pacific/Auckland", locale: "en-NZ" },
  { name: "New York (USA)", timezone: "America/New_York", locale: "en-US" },
  { name: "Portugal", timezone: "Europe/Lisbon", locale: "pt-PT" },
  { name: "Russia (Moscow)", timezone: "Europe/Moscow", locale: "ru-RU" },
  { name: "Romania", timezone: "Europe/Bucharest", locale: "ro-RO" },
  { name: "Singapore", timezone: "Asia/Singapore", locale: "en-SG" },
  { name: "Turkey", timezone: "Europe/Istanbul", locale: "tr-TR" },
  { name: "Ukraine", timezone: "Europe/Kiev", locale: "uk-UA" },
  {
    name: "USA (Los Angeles)",
    timezone: "America/Los_Angeles",
    locale: "en-US",
  },
  { name: "USA (Chicago)", timezone: "America/Chicago", locale: "en-US" },
  { name: "USA (Denver)", timezone: "America/Denver", locale: "en-US" },
  {
    name: "Vietnam (Ho Chi Minh)",
    timezone: "Asia/Ho_Chi_Minh",
    locale: "vi-VN",
  },
  { name: "Thailand (Bangkok)", timezone: "Asia/Bangkok", locale: "th-TH" },
  { name: "United Kingdom", timezone: "Europe/London", locale: "en-GB" },
  {
    name: "Saudi Arabia (Riyadh)",
    timezone: "Asia/Riyadh",
    locale: "ar-SA",
  },
  { name: "Philippines (Manila)", timezone: "Asia/Manila", locale: "fil-PH" },
  {
    name: "Malaysia (Kuala Lumpur)",
    timezone: "Asia/Kuala_Lumpur",
    locale: "ms-MY",
  },
  { name: "Pakistan (Karachi)", timezone: "Asia/Karachi", locale: "ur-PK" },
  { name: "Bangladesh (Dhaka)", timezone: "Asia/Dhaka", locale: "bn-BD" },
  { name: "Hong Kong", timezone: "Asia/Hong_Kong", locale: "zh-HK" },
  {
    name: "Mongolia (Ulaanbaatar)",
    timezone: "Asia/Ulaanbaatar",
    locale: "mn-MN",
  },
  { name: "Nepal (Kathmandu)", timezone: "Asia/Kathmandu", locale: "ne-NP" },
  { name: "Sri Lanka (Colombo)", timezone: "Asia/Colombo", locale: "si-LK" },
  { name: "Myanmar (Yangon)", timezone: "Asia/Yangon", locale: "my-MM" },
  {
    name: "Cambodia (Phnom Penh)",
    timezone: "Asia/Phnom_Penh",
    locale: "km-KH",
  },
  { name: "Laos (Vientiane)", timezone: "Asia/Vientiane", locale: "lo-LA" },
  {
    name: "South Africa (Johannesburg)",
    timezone: "Africa/Johannesburg",
    locale: "en-ZA",
  },
  { name: "Kenya (Nairobi)", timezone: "Africa/Nairobi", locale: "sw-KE" },
  { name: "Nigeria (Lagos)", timezone: "Africa/Lagos", locale: "en-NG" },
  {
    name: "Argentina (Buenos Aires)",
    timezone: "America/Argentina/Buenos_Aires",
    locale: "es-AR",
  },
  { name: "Chile (Santiago)", timezone: "America/Santiago", locale: "es-CL" },
  { name: "Colombia (Bogota)", timezone: "America/Bogota", locale: "es-CO" },
  { name: "Peru (Lima)", timezone: "America/Lima", locale: "es-PE" },
  {
    name: "Australia (Melbourne)",
    timezone: "Australia/Melbourne",
    locale: "en-AU",
  },
  { name: "Australia (Perth)", timezone: "Australia/Perth", locale: "en-AU" },
];
